### ISSUE TITLE
A `warning` is observed when tracing with database endpoint

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/module-ballerinax-jaeger#139]
See the attached image for more details.

<img width="786" alt="Screenshot 2023-02-08 at 12 48 49" src="https://user-images.githubusercontent.com/6178058/217461342-15b85030-1069-4684-8653-e418dd479e3c.png">

Use the below code to reproduce the issue.
https://github.com/shafreenAnfar/springboot-and-ballerina/tree/main/ballerina-user-rest-service

**Comment by NipunaMadhushan** [comment]
This issue had occured in other projects as well (other than Ballerina). 
There were discussions about the issue in https://github.com/jaegertracing/jaeger/issues/2321 and https://github.com/open-telemetry/opentelemetry-collector/issues/878. But nothing seems to be working even with the opentelemetry release `1.0.0` which ballerina use.

**Comment by NipunaMadhushan** [comment]
When I tried to bump the opentelemetry version to latest versions, following issue occurred. 

```
[2023-05-26 11:23:23,359] SEVERE {b7a.log.crash} - 'io.opentelemetry.api.metrics.LongCounterBuilder io.opentelemetry.api.metrics.Meter.longCounterBuilder(java.lang.String)' 
java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.LongCounterBuilder io.opentelemetry.api.metrics.Meter.longCounterBuilder(java.lang.String)'
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.<init>(OtlpGrpcSpanExporter.java:64)
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:188)
        at io.ballerina.observe.trace.jaeger.JaegerTracerProvider.initializeConfigurations(JaegerTracerProvider.java:73)
        at ballerinax.jaeger.0.tracer_provider.externInitializeConfigurations(tracer_provider.bal:47)
        at ballerinax.jaeger.0.tracer_provider.init(tracer_provider.bal:42)
        at ballerinax.jaeger.0.$_init.$gen$$0046$0060init$0062(jaeger:1)
        at nipunal.issue_test.0.$_init.$moduleInit(issue_test)
        at nipunal.issue_test.0.$_init.$moduleExecute(issue_test)
        at nipunal.issue_test.0.$_init.$lambda$$moduleExecute$(issue_test)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
